/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kuis2;
import static javax.swing.JOptionPane.showMessageDialog;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author FlaB
 */
public class FormDaftar extends javax.swing.JFrame {

    /**
     * Creates new form FormDaftar
     */
    public FormDaftar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        labelNIK = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelJK = new javax.swing.JLabel();
        labelHobby = new javax.swing.JLabel();
        labePhoneNumber = new javax.swing.JLabel();
        labelTanggalLahir = new javax.swing.JLabel();
        fieldNIK = new javax.swing.JTextField();
        fieldNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldAlamat = new javax.swing.JTextArea();
        radioLk = new javax.swing.JRadioButton();
        radioPr = new javax.swing.JRadioButton();
        jCheckBoxHobby1 = new javax.swing.JCheckBox();
        jCheckBoxHobby2 = new javax.swing.JCheckBox();
        jCheckBoxHobby3 = new javax.swing.JCheckBox();
        fieldPhoneNumber = new javax.swing.JTextField();
        fieldBirthDate = new javax.swing.JTextField();
        labelPendidikan = new javax.swing.JLabel();
        comboBoxPendidikan = new javax.swing.JComboBox<>();
        labelIPK = new javax.swing.JLabel();
        fieldIPK = new javax.swing.JTextField();
        buttonDaftar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNIK.setText("NIK");

        labelNama.setText("Nama");

        labelAlamat.setText("Alamat");

        labelJK.setText("Jenis Kelamin");

        labelHobby.setText("Hobby");

        labePhoneNumber.setText("No Telp");

        labelTanggalLahir.setText("Tanggal Lahir");

        fieldNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNIKActionPerformed(evt);
            }
        });

        fieldAlamat.setColumns(20);
        fieldAlamat.setRows(5);
        jScrollPane1.setViewportView(fieldAlamat);

        buttonGroup1.add(radioLk);
        radioLk.setText("Laki-laki");
        radioLk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLkActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioPr);
        radioPr.setText("Perempuan");

        jCheckBoxHobby1.setText("Ngoding");

        jCheckBoxHobby2.setText("Main Game");

        jCheckBoxHobby3.setText("Nonton Anime");

        labelPendidikan.setText("Pendidikan");

        comboBoxPendidikan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "D1", "D2", "D3", "D4 / S1", "S2", "S3" }));
        comboBoxPendidikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPendidikanActionPerformed(evt);
            }
        });

        labelIPK.setText("IPK");

        buttonDaftar.setText("Daftar");
        buttonDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDaftarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNIK)
                    .addComponent(labelNama)
                    .addComponent(labePhoneNumber)
                    .addComponent(labelHobby)
                    .addComponent(labelJK)
                    .addComponent(labelAlamat)
                    .addComponent(labelTanggalLahir)
                    .addComponent(labelPendidikan)
                    .addComponent(labelIPK))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxPendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonDaftar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBoxHobby3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(fieldNama)
                            .addComponent(fieldNIK)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioLk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioPr))
                            .addComponent(jCheckBoxHobby1)
                            .addComponent(jCheckBoxHobby2)
                            .addComponent(fieldPhoneNumber)
                            .addComponent(fieldBirthDate)))
                    .addComponent(fieldIPK, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNIK)
                    .addComponent(fieldNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJK)
                    .addComponent(radioLk)
                    .addComponent(radioPr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHobby)
                    .addComponent(jCheckBoxHobby1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxHobby2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxHobby3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labePhoneNumber)
                    .addComponent(fieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTanggalLahir)
                    .addComponent(fieldBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxPendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPendidikan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIPK)
                    .addComponent(fieldIPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(buttonDaftar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNIKActionPerformed

    private void comboBoxPendidikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPendidikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPendidikanActionPerformed

    private void buttonDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDaftarActionPerformed
        String NIK = fieldNIK.getText();
        String nama = fieldNama.getText();
        String alamat = fieldAlamat.getText();
        String jenisKelamin = null;
        if (radioLk.isSelected()) {
            jenisKelamin = radioLk.getText();
        } else if (radioPr.isSelected()) {
            jenisKelamin = radioPr.getText();
        }
        
        StringBuilder hobbies = new StringBuilder();
        if (jCheckBoxHobby1.isSelected()) {
            hobbies.append(jCheckBoxHobby1.getText()).append(", ");
        }
        if (jCheckBoxHobby2.isSelected()) {
            hobbies.append(jCheckBoxHobby2.getText()).append(", ");
        }
        if (jCheckBoxHobby3.isSelected()) {
            hobbies.append(jCheckBoxHobby3.getText());
        }
        
        String phoneNumber = fieldPhoneNumber.getText();
        try {
            Long.parseLong(phoneNumber);
        } catch (NumberFormatException e) {
            showMessageDialog(null, "Nomor telepon harus berupa angka!");
            return;
        }
        
        String birthDate = fieldBirthDate.getText();
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date birth = sdf.parse(birthDate);
            Calendar birthCal = Calendar.getInstance();
            birthCal.setTime(birth);
            
            Calendar now = Calendar.getInstance();
            int age = now.get(Calendar.YEAR) - birthCal.get(Calendar.YEAR);
            if (now.get(Calendar.DAY_OF_YEAR) < birthCal.get(Calendar.DAY_OF_YEAR)) {
                age--;
            }
            
            if (age < 18) {
                showMessageDialog(null, "Anda belum cukup umur untuk melamar pekerjaan ini");
                return;
            }
        } catch (ParseException e) {
            showMessageDialog(null, "Format tanggal lahir tidak valid! Gunakan format dd/MM/yyyy");
            return;
        }
        
        String ipkStr = fieldIPK.getText();
        try {
            double ipk = Double.parseDouble(ipkStr);
            if (ipk < 0.00 || ipk > 4.00) {
                showMessageDialog(null, "IPK tidak valid");
                return;
            }
        } catch (NumberFormatException e) {
            showMessageDialog(null, "IPK tidak valid");
            return;
        }
        
        if (NIK.isEmpty() || nama.isEmpty() || alamat.isEmpty() || jenisKelamin == null || 
            phoneNumber.isEmpty() || birthDate.isEmpty() || ipkStr.isEmpty()) {
            showMessageDialog(null, "Semua field harus diisi!");
            return;
        }
        
        showMessageDialog(null, "Anda berhasil mendaftar");
        
        fieldNIK.setText("");
        fieldNama.setText("");
        fieldAlamat.setText("");
        buttonGroup1.clearSelection();
        jCheckBoxHobby1.setSelected(false);
        jCheckBoxHobby2.setSelected(false);
        jCheckBoxHobby3.setSelected(false);
        fieldPhoneNumber.setText("");
        fieldBirthDate.setText("");
        comboBoxPendidikan.setSelectedIndex(0);
        fieldIPK.setText("");
    }//GEN-LAST:event_buttonDaftarActionPerformed

    private void radioLkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDaftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDaftar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> comboBoxPendidikan;
    private javax.swing.JTextArea fieldAlamat;
    private javax.swing.JTextField fieldBirthDate;
    private javax.swing.JTextField fieldIPK;
    private javax.swing.JTextField fieldNIK;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldPhoneNumber;
    private javax.swing.JCheckBox jCheckBoxHobby1;
    private javax.swing.JCheckBox jCheckBoxHobby2;
    private javax.swing.JCheckBox jCheckBoxHobby3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labePhoneNumber;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelHobby;
    private javax.swing.JLabel labelIPK;
    private javax.swing.JLabel labelJK;
    private javax.swing.JLabel labelNIK;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPendidikan;
    private javax.swing.JLabel labelTanggalLahir;
    private javax.swing.JRadioButton radioLk;
    private javax.swing.JRadioButton radioPr;
    // End of variables declaration//GEN-END:variables
}
